--rta reverse table
CREATE SEQUENCE rta_reverse_feed_details_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

DROP TABLE IF EXISTS rta_reverse_feed_details;
CREATE TABLE rta_reverse_feed_details
(
  id          bigint PRIMARY KEY DEFAULT nextval('rta_reverse_feed_details_id_seq'::regclass),
reg_code character varying,
client_id integer,
client_name character varying,
broker_code varchar,
amc_code character varying,
scheme_code varchar,
security_name varchar,
folio_no character varying,
trant_type character varying,
order_date character varying,
qty double precision,
amount double precision,
status character varying,
remarks character varying,
order_id integer,
user_trxn_no integer,
nom_status character varying default 'generate',
aof_status character varying default 'generate', 
nom_tiff_size  character varying default 'N/A',
aof_tiff_size  character varying default 'N/A',
nom_downloaded_on timestamptz  DEFAULT NULL,
aof_downloaded_on timestamptz  DEFAULT NULL,
  is_active               boolean default true,
  created_at              timestamptz         DEFAULT (now() AT TIME ZONE 'UTC'),
  created_by              integer             default 1,
  updated_at              timestamptz         DEFAULT (now() AT TIME ZONE 'UTC'),
  updated_by              integer             default 1
);


drop table if exists rta_reverse_feed_details_log;
CREATE TABLE rta_reverse_feed_details_log
(
  log_id        BIGINT PRIMARY KEY,
  dml_action    char(1) NOT NULL CHECK (dml_action IN ('I', 'D', 'U')),
  log_timestamp timestamptz,
  id      bigint,
reg_code character varying,
client_id integer,
client_name character varying,
broker_code varchar,
amc_code character varying,
scheme_code varchar,
security_name varchar,
folio_no character varying,
trant_type character varying,
order_date character varying,
qty double precision,
amount double precision,
status character varying,
remarks character varying,
order_id integer,
user_trxn_no integer,
nom_status character varying default 'generate',
aof_status character varying default 'generate', 
nom_tiff_size  character varying default 'N/A',
aof_tiff_size  character varying default 'N/A',
nom_downloaded_on timestamptz  DEFAULT NULL,
aof_downloaded_on timestamptz  DEFAULT NULL,
  is_active               boolean default true,
  created_at              timestamptz         DEFAULT (now() AT TIME ZONE 'UTC'),
  created_by              integer             default 1,
  updated_at              timestamptz         DEFAULT (now() AT TIME ZONE 'UTC'),
  updated_by              integer             default 1
);

CREATE SEQUENCE rta_reverse_feed_details_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

    CREATE TRIGGER last_updated BEFORE UPDATE ON rta_reverse_feed_details FOR EACH ROW EXECUTE PROCEDURE last_updated();
    CREATE TRIGGER texple_audit AFTER INSERT OR UPDATE OR DELETE ON rta_reverse_feed_details FOR EACH ROW EXECUTE PROCEDURE texple_audit('rta_reverse_feed_details_log_id_seq');


--client_ master

CREATE SEQUENCE client_master_id_seq

    START WITH 1

    INCREMENT BY 1

    NO MINVALUE

    NO MAXVALUE

    CACHE 1;



Drop TABLE if exists client_master;

CREATE TABLE client_master (
    id BIGINT PRIMARY KEY DEFAULT nextval('client_master_id_seq'::regclass),
    client_id BIGINT,
    client_name CHARACTER VARYING,
    client_code CHARACTER VARYING,
    client_type CHARACTER VARYING,
    account_type CHARACTER VARYING,
    account_open_date CHARACTER VARYING,
    inception_date CHARACTER VARYING,
    performance_reporting_date CHARACTER VARYING,
    charge_upto CHARACTER VARYING,
    maturity_date CHARACTER VARYING,
    account_closure_date CHARACTER VARYING,
    account_closing_reason CHARACTER VARYING,
    birth_date CHARACTER VARYING,
    contact_name CHARACTER VARYING,
    phone_home CHARACTER VARYING,
    phone_work CHARACTER VARYING,
    mobile CHARACTER VARYING,
    email CHARACTER VARYING,
    fax CHARACTER VARYING,
    address_1 CHARACTER VARYING,
    address_2 CHARACTER VARYING,
    city CHARACTER VARYING,
    pin_code CHARACTER VARYING,
    state CHARACTER VARYING,
    mail_address_1 CHARACTER VARYING,
    mail_address_2 CHARACTER VARYING,
    mail_city CHARACTER VARYING,
    mail_pincode CHARACTER VARYING,
    mail_state CHARACTER VARYING,
    pan_number CHARACTER VARYING,
    ward CHARACTER VARYING,
    circle CHARACTER VARYING,
    tan_number CHARACTER VARYING,
    ref_code_1 CHARACTER VARYING,
    ref_code_2 CHARACTER VARYING,
    ref_code_3 CHARACTER VARYING,
    ref_code_4 CHARACTER VARYING,
    dir_1_name CHARACTER VARYING,
    dir_1_map_in CHARACTER VARYING,
    dir_2_name CHARACTER VARYING,
    dir_2_map_in CHARACTER VARYING,
    dir_3_name CHARACTER VARYING,
    dir_3_map_in CHARACTER VARYING,
    occupation CHARACTER VARYING,
    status CHARACTER VARYING,
    owner_id CHARACTER VARYING,
    owner_name CHARACTER VARYING,
    group_id CHARACTER VARYING,
    group_name CHARACTER VARYING,
    intermediary_id CHARACTER VARYING,
    intermediary_name CHARACTER VARYING,
    scheme_id CHARACTER VARYING,
    scheme_name CHARACTER VARYING,
    fund_mgr_id CHARACTER VARYING,
    fund_mgr_name CHARACTER VARYING,
    branch_id CHARACTER VARYING,
    branch_name CHARACTER VARYING,
    rel_mgr_id CHARACTER VARYING,
    rel_mgr_name CHARACTER VARYING,
    advisor_id CHARACTER VARYING,
    advisor_name CHARACTER VARYING,
    user_name CHARACTER VARYING,
    broker_account_id CHARACTER VARYING,
    trading_bank_code CHARACTER VARYING,
    trading_bank_account CHARACTER VARYING,
    trading_custody_code CHARACTER VARYING,
    trading_custody_dp CHARACTER VARYING,
    trading_custody_account_id CHARACTER VARYING,
    client_bank_code CHARACTER VARYING,
    client_bank_account CHARACTER VARYING,
    client_custody_code CHARACTER VARYING,
    client_custody_dp CHARACTER VARYING,
    client_custody_account_id CHARACTER VARYING,
    client_custody_scheme_code CHARACTER VARYING,
    bill_group CHARACTER VARYING,
    tds_on_fees CHARACTER VARYING,
    daily_expense_accrual CHARACTER VARYING,
    fee_payment_mode CHARACTER VARYING,
    incentive CHARACTER VARYING,
    mandate_bank_name CHARACTER VARYING,
    mandate_bank_branch_name CHARACTER VARYING,
    mandate_bank_account_type CHARACTER VARYING,
    mandate_bank_account_no CHARACTER VARYING,
    mandate_micr CHARACTER VARYING,
    mandate_rtgs CHARACTER VARYING,
    mandate_neft CHARACTER VARYING,
    mandate_depository CHARACTER VARYING,
    mandate_dp CHARACTER VARYING,
    mandate_dp_name CHARACTER VARYING,
    mandate_dp_client_id CHARACTER VARYING,
    salutation CHARACTER VARYING,
    first_name CHARACTER VARYING,
    middle_name CHARACTER VARYING,
    last_name CHARACTER VARYING,
    first_holder_gender CHARACTER VARYING,
    father_husband CHARACTER VARYING,
    joint1_name CHARACTER VARYING,
    joint1_father_husband CHARACTER VARYING,
    joint1_pan CHARACTER VARYING,
    joint2_name CHARACTER VARYING,
    joint2_father_husband CHARACTER VARYING,
    joint2_pan CHARACTER VARYING,
    nominee_name CHARACTER VARYING,
    guardian_name CHARACTER VARYING,
    second_holder_name CHARACTER VARYING,
    second_holder_pan CHARACTER VARYING,
    second_holder_relation CHARACTER VARYING,
    second_holder_dob CHARACTER VARYING,
    second_holder_gender CHARACTER VARYING,
    second_holder_father_husband CHARACTER VARYING,
    second_holder_status CHARACTER VARYING,
    second_holder_occupation CHARACTER VARYING,
    second_holder_bank_name CHARACTER VARYING,
    second_holder_branch_name CHARACTER VARYING,
    second_holder_bank_account_no CHARACTER VARYING,
    second_holder_bank_acc_type CHARACTER VARYING,
    second_holder_micr_number CHARACTER VARYING,
    second_holder_neft_code CHARACTER VARYING,
    second_holder_rtgs_code CHARACTER VARYING,
    second_holder_depository CHARACTER VARYING,
    second_holder_dp_id CHARACTER VARYING,
    second_holder_dp_name CHARACTER VARYING,
    second_holder_dp_client_id CHARACTER VARYING,
    third_holder_name CHARACTER VARYING,
    third_holder_pan_no CHARACTER VARYING,
    third_holder_relation CHARACTER VARYING,
    third_holder_dob CHARACTER VARYING,
    third_holder_gender CHARACTER VARYING,
    third_holder_father_husband CHARACTER VARYING,
    third_holder_status CHARACTER VARYING,
    third_holder_occupation CHARACTER VARYING,
    third_holder_bank_name CHARACTER VARYING,
    third_holder_branch_name CHARACTER VARYING,
    third_holder_bank_account_no CHARACTER VARYING,
    third_holder_bank_acc_type CHARACTER VARYING,
    third_holder_micr_number CHARACTER VARYING,
    third_holder_neft_code CHARACTER VARYING,
    third_holder_rtgs_code CHARACTER VARYING,
    third_holder_depository CHARACTER VARYING,
    third_holder_dp_id CHARACTER VARYING,
    third_holder_dp_name CHARACTER VARYING,
    third_holder_dp_client_id CHARACTER VARYING,
    accounting_txn CHARACTER VARYING,
    stt_taken_as CHARACTER VARYING,
    trxn_taken_as CHARACTER VARYING,
    skip_from_mf_corporate_action CHARACTER VARYING,
    head_of_family CHARACTER VARYING,
    country CHARACTER VARYING,
    nationality CHARACTER VARYING,
    capital_committed CHARACTER VARYING,
    mail_phone_home CHARACTER VARYING,
    mail_phone_work CHARACTER VARYING,
    mail_mobile CHARACTER VARYING,
    mail_fax CHARACTER VARYING,
    mail_email_id CHARACTER VARYING,
    share_reports_flag CHARACTER VARYING,
    arn_id CHARACTER VARYING,
    arn_name CHARACTER VARYING,
    wealth_advisor_id CHARACTER VARYING,
    wealth_advisor_name CHARACTER VARYING,
    first_holder_kyc CHARACTER VARYING,
    first_holder_aadhar CHARACTER VARYING,
    first_holder_fatca CHARACTER VARYING,
    first_holder_ubo CHARACTER VARYING,
    second_holder_kyc CHARACTER VARYING,
    second_holder_aadhar CHARACTER VARYING,
    second_holder_fatca CHARACTER VARYING,
    second_holder_ubo CHARACTER VARYING,
    third_holder_kyc CHARACTER VARYING,
    third_holder_aadhar CHARACTER VARYING,
    third_holder_fatca CHARACTER VARYING,
    third_holder_ubo CHARACTER VARYING,
    mode_of_holding CHARACTER VARYING,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT (NOW() AT TIME ZONE 'UTC'::TEXT),
    created_by INTEGER DEFAULT 1,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT (NOW() AT TIME ZONE 'UTC'::TEXT),
    updated_by INTEGER DEFAULT 1
);



Drop TABLE if exists client_master_log;

CREATE TABLE client_master_log (
    log_id      BIGINT PRIMARY KEY,
    dml_action    char(1) NOT NULL CHECK (dml_action IN ('I', 'D', 'U')),
    log_timestamp timestamptz,
    id      bigint,
    client_id BIGINT,
    client_name CHARACTER VARYING,
    client_code CHARACTER VARYING,
    client_type CHARACTER VARYING,
    account_type CHARACTER VARYING,
    account_open_date CHARACTER VARYING,
    inception_date CHARACTER VARYING,
    performance_reporting_date CHARACTER VARYING,
    charge_upto CHARACTER VARYING,
    maturity_date CHARACTER VARYING,
    account_closure_date CHARACTER VARYING,
    account_closing_reason CHARACTER VARYING,
    birth_date CHARACTER VARYING,
    contact_name CHARACTER VARYING,
    phone_home CHARACTER VARYING,
    phone_work CHARACTER VARYING,
    mobile CHARACTER VARYING,
    email CHARACTER VARYING,
    fax CHARACTER VARYING,
    address_1 CHARACTER VARYING,
    address_2 CHARACTER VARYING,
    city CHARACTER VARYING,
    pin_code CHARACTER VARYING,
    state CHARACTER VARYING,
    mail_address_1 CHARACTER VARYING,
    mail_address_2 CHARACTER VARYING,
    mail_city CHARACTER VARYING,
    mail_pincode CHARACTER VARYING,
    mail_state CHARACTER VARYING,
    pan_number CHARACTER VARYING,
    ward CHARACTER VARYING,
    circle CHARACTER VARYING,
    tan_number CHARACTER VARYING,
    ref_code_1 CHARACTER VARYING,
    ref_code_2 CHARACTER VARYING,
    ref_code_3 CHARACTER VARYING,
    ref_code_4 CHARACTER VARYING,
    dir_1_name CHARACTER VARYING,
    dir_1_map_in CHARACTER VARYING,
    dir_2_name CHARACTER VARYING,
    dir_2_map_in CHARACTER VARYING,
    dir_3_name CHARACTER VARYING,
    dir_3_map_in CHARACTER VARYING,
    occupation CHARACTER VARYING,
    status CHARACTER VARYING,
    owner_id CHARACTER VARYING,
    owner_name CHARACTER VARYING,
    group_id CHARACTER VARYING,
    group_name CHARACTER VARYING,
    intermediary_id CHARACTER VARYING,
    intermediary_name CHARACTER VARYING,
    scheme_id CHARACTER VARYING,
    scheme_name CHARACTER VARYING,
    fund_mgr_id CHARACTER VARYING,
    fund_mgr_name CHARACTER VARYING,
    branch_id CHARACTER VARYING,
    branch_name CHARACTER VARYING,
    rel_mgr_id CHARACTER VARYING,
    rel_mgr_name CHARACTER VARYING,
    advisor_id CHARACTER VARYING,
    advisor_name CHARACTER VARYING,
    user_name CHARACTER VARYING,
    broker_account_id CHARACTER VARYING,
    trading_bank_code CHARACTER VARYING,
    trading_bank_account CHARACTER VARYING,
    trading_custody_code CHARACTER VARYING,
    trading_custody_dp CHARACTER VARYING,
    trading_custody_account_id CHARACTER VARYING,
    client_bank_code CHARACTER VARYING,
    client_bank_account CHARACTER VARYING,
    client_custody_code CHARACTER VARYING,
    client_custody_dp CHARACTER VARYING,
    client_custody_account_id CHARACTER VARYING,
    client_custody_scheme_code CHARACTER VARYING,
    bill_group CHARACTER VARYING,
    tds_on_fees CHARACTER VARYING,
    daily_expense_accrual CHARACTER VARYING,
    fee_payment_mode CHARACTER VARYING,
    incentive CHARACTER VARYING,
    mandate_bank_name CHARACTER VARYING,
    mandate_bank_branch_name CHARACTER VARYING,
    mandate_bank_account_type CHARACTER VARYING,
    mandate_bank_account_no CHARACTER VARYING,
    mandate_micr CHARACTER VARYING,
    mandate_rtgs CHARACTER VARYING,
    mandate_neft CHARACTER VARYING,
    mandate_depository CHARACTER VARYING,
    mandate_dp CHARACTER VARYING,
    mandate_dp_name CHARACTER VARYING,
    mandate_dp_client_id CHARACTER VARYING,
    salutation CHARACTER VARYING,
    first_name CHARACTER VARYING,
    middle_name CHARACTER VARYING,
    last_name CHARACTER VARYING,
    first_holder_gender CHARACTER VARYING,
    father_husband CHARACTER VARYING,
    joint1_name CHARACTER VARYING,
    joint1_father_husband CHARACTER VARYING,
    joint1_pan CHARACTER VARYING,
    joint2_name CHARACTER VARYING,
    joint2_father_husband CHARACTER VARYING,
    joint2_pan CHARACTER VARYING,
    nominee_name CHARACTER VARYING,
    guardian_name CHARACTER VARYING,
    second_holder_name CHARACTER VARYING,
    second_holder_pan CHARACTER VARYING,
    second_holder_relation CHARACTER VARYING,
    second_holder_dob CHARACTER VARYING,
    second_holder_gender CHARACTER VARYING,
    second_holder_father_husband CHARACTER VARYING,
    second_holder_status CHARACTER VARYING,
    second_holder_occupation CHARACTER VARYING,
    second_holder_bank_name CHARACTER VARYING,
    second_holder_branch_name CHARACTER VARYING,
    second_holder_bank_account_no CHARACTER VARYING,
    second_holder_bank_acc_type CHARACTER VARYING,
    second_holder_micr_number CHARACTER VARYING,
    second_holder_neft_code CHARACTER VARYING,
    second_holder_rtgs_code CHARACTER VARYING,
    second_holder_depository CHARACTER VARYING,
    second_holder_dp_id CHARACTER VARYING,
    second_holder_dp_name CHARACTER VARYING,
    second_holder_dp_client_id CHARACTER VARYING,
    third_holder_name CHARACTER VARYING,
    third_holder_pan_no CHARACTER VARYING,
    third_holder_relation CHARACTER VARYING,
    third_holder_dob CHARACTER VARYING,
    third_holder_gender CHARACTER VARYING,
    third_holder_father_husband CHARACTER VARYING,
    third_holder_status CHARACTER VARYING,
    third_holder_occupation CHARACTER VARYING,
    third_holder_bank_name CHARACTER VARYING,
    third_holder_branch_name CHARACTER VARYING,
    third_holder_bank_account_no CHARACTER VARYING,
    third_holder_bank_acc_type CHARACTER VARYING,
    third_holder_micr_number CHARACTER VARYING,
    third_holder_neft_code CHARACTER VARYING,
    third_holder_rtgs_code CHARACTER VARYING,
    third_holder_depository CHARACTER VARYING,
    third_holder_dp_id CHARACTER VARYING,
    third_holder_dp_name CHARACTER VARYING,
    third_holder_dp_client_id CHARACTER VARYING,
    accounting_txn CHARACTER VARYING,
    stt_taken_as CHARACTER VARYING,
    trxn_taken_as CHARACTER VARYING,
    skip_from_mf_corporate_action CHARACTER VARYING,
    head_of_family CHARACTER VARYING,
    country CHARACTER VARYING,
    nationality CHARACTER VARYING,
    capital_committed CHARACTER VARYING,
    mail_phone_home CHARACTER VARYING,
    mail_phone_work CHARACTER VARYING,
    mail_mobile CHARACTER VARYING,
    mail_fax CHARACTER VARYING,
    mail_email_id CHARACTER VARYING,
    share_reports_flag CHARACTER VARYING,
    arn_id CHARACTER VARYING,
    arn_name CHARACTER VARYING,
    wealth_advisor_id CHARACTER VARYING,
    wealth_advisor_name CHARACTER VARYING,
    first_holder_kyc CHARACTER VARYING,
    first_holder_aadhar CHARACTER VARYING,
    first_holder_fatca CHARACTER VARYING,
    first_holder_ubo CHARACTER VARYING,
    second_holder_kyc CHARACTER VARYING,
    second_holder_aadhar CHARACTER VARYING,
    second_holder_fatca CHARACTER VARYING,
    second_holder_ubo CHARACTER VARYING,
    third_holder_kyc CHARACTER VARYING,
    third_holder_aadhar CHARACTER VARYING,
    third_holder_fatca CHARACTER VARYING,
    third_holder_ubo CHARACTER VARYING,
    mode_of_holding CHARACTER VARYING,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT (NOW() AT TIME ZONE 'UTC'::TEXT),
    created_by INTEGER DEFAULT 1,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT (NOW() AT TIME ZONE 'UTC'::TEXT),
    updated_by INTEGER DEFAULT 1
);

CREATE SEQUENCE client_master_log_id_seq

    START WITH 1

    INCREMENT BY 1

    NO MINVALUE

    NO MAXVALUE

    CACHE 1;

    CREATE TRIGGER last_updated BEFORE UPDATE ON client_master FOR EACH ROW EXECUTE PROCEDURE last_updated();
    CREATE TRIGGER texple_audit AFTER INSERT OR UPDATE OR DELETE ON client_master FOR EACH ROW EXECUTE PROCEDURE texple_audit('client_master_log_id_seq');


    --karvy table
    
    CREATE SEQUENCE karvy_reverse_field_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
    
   DROP TABLE IF EXISTS karvy_reverse_field;
CREATE TABLE karvy_reverse_field
(
  id          bigint PRIMARY KEY DEFAULT nextval('karvy_reverse_field_id_seq'::regclass), 
  portremarks character varying,
  amc_code character varying,
  broke_cd character varying,
  sbbr_code character varying,
  user_code character varying,
  usr_txn_no bigint,
  appl_no character varying,
  folio_no character varying,
  ck_dig_no character varying,
  trxn_type character varying,
  sch_code character varying,
  fh_name character varying,
  j1_name character varying,
  j2_name character varying,
  add1 character varying,
  add2 character varying,
  add3 character varying,
  city character varying,
  pincode character varying,
  phone_off character varying,
  trxn_date character varying,
  trxn_time character varying,
  units character varying,
  amount character varying,
  clos_ac_ch character varying,
  fh_dob character varying,
  guardian character varying,
  tax_number character varying,
  phone_res character varying,
  fax_off character varying,
  fax_res character varying,
  email character varying,
  acc_no character varying,
  acct_type character varying,
  bank_name character varying,
  br_name character varying,
  bank_city character varying,
  reinv_tag character varying,
  hold_natur character varying,
  occ_code character varying,
  tax_status character varying,
  remarks character varying,
  state character varying,
  sub_trxn_t character varying,
  micr_cd character varying,
  pay_mec character varying,
  pricing character varying,
  pan_2_hldr character varying,
  pan_3_hldr character varying,
  nom_name character varying,
  nom_rela character varying,
  guard_pan character varying,
  fh_gndr character varying,
  sip_rgdt character varying,
  ifsc_code character varying,
  mobile_no character varying,
  dp_id character varying,
  nri_add1 character varying,
  nri_add2 character varying,
  nri_add3 character varying,
  nri_city character varying,
  nri_state character varying,
  nri_con character varying,
  nri_pin character varying,
  nom_per character varying,
  nom2_name character varying,
  nom2_rel character varying,
  nom2_per character varying,
  nom3_name character varying,
  nom3_rel character varying,
  nom3_per character varying,
  nri_add_fl character varying,
  firc_stat character varying,
  sip_rfno character varying,
  no_inst character varying,
  sip_fq character varying,
  sip_st_dt character varying,
  sip_end_dt character varying,
  inst_num character varying,
  nom1_dob character varying,
  nom1_min_f character varying,
  nom1_guard character varying,
  nom2_dob character varying,
  nom2_min_f character varying,
  nom2_guard character varying,
  nom3_dob character varying,
  nom3_min_f character varying,
  nom3_guard character varying,
  fh_pan_exm character varying,
  j1_pan_exm character varying,
  j2_pan_exm character varying,
  gd_pan_exm character varying,
  fh_exm_cat character varying,
  j1_exm_cat character varying,
  j2_exm_cat character varying,
  gd_exm_cat character varying,
  fh_kra_exm character varying,
  j1_kra_exm character varying,
  j2_kra_exm character varying,
  gd_kra_exm character varying,
  euin_opt character varying,
  euin character varying,
  nom_opt character varying,
  sub_arn character varying,
  iin_no character varying,
  fh_ckyc_no character varying,
  j1_ckyc_no character varying,
  j2_ckyc_no character varying,
  gd_ckyc_no character varying,
  j1_dob character varying,
  j2_dob character varying,
  gd_dob character varying,
  brok_type character varying,
  inv_dp_id character varying,
  inv_pin_cd character varying,
  cust_const character varying,
  log_wt character varying,
  aof_ref character varying,
  nri_soff character varying,
  fatca_flag character varying,
  dpc character varying,
  us_cn_dcl character varying,
  isin character varying,
  credit_fl character varying,
  slf_fam_fl character varying,
  stlmnt_no character varying,
  pap_les_fl character varying,
  tac_flag character varying,
  altmt_mode character varying,
  sip_new character varying,
  sip_amt character varying,
  ft_acno character varying,
  depbank character varying,
  dep_acno character varying,
  dep_date character varying,
  dep_rfno character varying,
  suppl_flag character varying,
  th_pty_pay character varying,
  loc_cd character varying,
  instr_no character varying,
  kyc_flg character varying,
  trxn_mode character varying,
  dummy_1 character varying,
  dummy_2 character varying,
  dummy_3 character varying,
  dummy_4 character varying,
  dummy_5 character varying,
  dummy_6 character varying,
  dummy_7 character varying,
  dummy_8 character varying,
  dummy_9 character varying,
  dummy_10 character varying,
  dummy_11 character varying,
  dummy_12 character varying,
  dummy_13 character varying,
  dummy_14 character varying,
  dummy_15 character varying,
  dummy_16 character varying,
  dummy_17 character varying,
  dummy_18 character varying,
  dummy_19 character varying,
  dummy_20 character varying,
  dummy_21 character varying,
  dummy_22 character varying,
  dummy_23 character varying,
  dummy_24 character varying,
  dummy_25 character varying,
  dummy_26 character varying,
  dummy_27 character varying,
ih_no BIGINT, 
transaction_date character varying,
is_active                 boolean default true,
  created_at              timestamptz         DEFAULT (now() AT TIME ZONE 'UTC'),
  created_by              integer             default 1,
  updated_at              timestamptz         DEFAULT (now() AT TIME ZONE 'UTC'),
  updated_by              integer             default 1
  );

   DROP TABLE IF EXISTS karvy_reverse_field_log;
CREATE TABLE karvy_reverse_field_log
(
  log_id        BIGINT PRIMARY KEY,
  dml_action    char(1) NOT NULL CHECK (dml_action IN ('I', 'D', 'U')),
  log_timestamp timestamptz,
  id      bigint,
  portremarks character varying,
  amc_code character varying,
  broke_cd character varying,
  sbbr_code character varying,
  user_code character varying,
  usr_txn_no bigint,
  appl_no character varying,
  folio_no character varying,
  ck_dig_no character varying,
  trxn_type character varying,
  sch_code character varying,
  fh_name character varying,
  j1_name character varying,
  j2_name character varying,
  add1 character varying,
  add2 character varying,
  add3 character varying,
  city character varying,
  pincode character varying,
  phone_off character varying,
  trxn_date character varying,
  trxn_time character varying,
  units character varying,
  amount character varying,
  clos_ac_ch character varying,
  fh_dob character varying,
  guardian character varying,
  tax_number character varying,
  phone_res character varying,
  fax_off character varying,
  fax_res character varying,
  email character varying,
  acc_no character varying,
  acct_type character varying,
  bank_name character varying,
  br_name character varying,
  bank_city character varying,
  reinv_tag character varying,
  hold_natur character varying,
  occ_code character varying,
  tax_status character varying,
  remarks character varying,
  state character varying,
  sub_trxn_t character varying,
  micr_cd character varying,
  pay_mec character varying,
  pricing character varying,
  pan_2_hldr character varying,
  pan_3_hldr character varying,
  nom_name character varying,
  nom_rela character varying,
  guard_pan character varying,
  fh_gndr character varying,
  sip_rgdt character varying,
  ifsc_code character varying,
  mobile_no character varying,
  dp_id character varying,
  nri_add1 character varying,
  nri_add2 character varying,
  nri_add3 character varying,
  nri_city character varying,
  nri_state character varying,
  nri_con character varying,
  nri_pin character varying,
  nom_per character varying,
  nom2_name character varying,
  nom2_rel character varying,
  nom2_per character varying,
  nom3_name character varying,
  nom3_rel character varying,
  nom3_per character varying,
  nri_add_fl character varying,
  firc_stat character varying,
  sip_rfno character varying,
  no_inst character varying,
  sip_fq character varying,
  sip_st_dt character varying,
  sip_end_dt character varying,
  inst_num character varying,
  nom1_dob character varying,
  nom1_min_f character varying,
  nom1_guard character varying,
  nom2_dob character varying,
  nom2_min_f character varying,
  nom2_guard character varying,
  nom3_dob character varying,
  nom3_min_f character varying,
  nom3_guard character varying,
  fh_pan_exm character varying,
  j1_pan_exm character varying,
  j2_pan_exm character varying,
  gd_pan_exm character varying,
  fh_exm_cat character varying,
  j1_exm_cat character varying,
  j2_exm_cat character varying,
  gd_exm_cat character varying,
  fh_kra_exm character varying,
  j1_kra_exm character varying,
  j2_kra_exm character varying,
  gd_kra_exm character varying,
  euin_opt character varying,
  euin character varying,
  nom_opt character varying,
  sub_arn character varying,
  iin_no character varying,
  fh_ckyc_no character varying,
  j1_ckyc_no character varying,
  j2_ckyc_no character varying,
  gd_ckyc_no character varying,
  j1_dob character varying,
  j2_dob character varying,
  gd_dob character varying,
  brok_type character varying,
  inv_dp_id character varying,
  inv_pin_cd character varying,
  cust_const character varying,
  log_wt character varying,
  aof_ref character varying,
  nri_soff character varying,
  fatca_flag character varying,
  dpc character varying,
  us_cn_dcl character varying,
  isin character varying,
  credit_fl character varying,
  slf_fam_fl character varying,
  stlmnt_no character varying,
  pap_les_fl character varying,
  tac_flag character varying,
  altmt_mode character varying,
  sip_new character varying,
  sip_amt character varying,
  ft_acno character varying,
  depbank character varying,
  dep_acno character varying,
  dep_date character varying,
  dep_rfno character varying,
  suppl_flag character varying,
  th_pty_pay character varying,
  loc_cd character varying,
  instr_no character varying,
  kyc_flg character varying,
  trxn_mode character varying,
  dummy_1 character varying,
  dummy_2 character varying,
  dummy_3 character varying,
  dummy_4 character varying,
  dummy_5 character varying,
  dummy_6 character varying,
  dummy_7 character varying,
  dummy_8 character varying,
  dummy_9 character varying,
  dummy_10 character varying,
  dummy_11 character varying,
  dummy_12 character varying,
  dummy_13 character varying,
  dummy_14 character varying,
  dummy_15 character varying,
  dummy_16 character varying,
  dummy_17 character varying,
  dummy_18 character varying,
  dummy_19 character varying,
  dummy_20 character varying,
  dummy_21 character varying,
  dummy_22 character varying,
  dummy_23 character varying,
  dummy_24 character varying,
  dummy_25 character varying,
  dummy_26 character varying,
  dummy_27 character varying,
ih_no BIGINT, 
transaction_date character varying,
is_active                 boolean default true,
  created_at              timestamptz         DEFAULT (now() AT TIME ZONE 'UTC'),
  created_by              integer             default 1,
  updated_at              timestamptz         DEFAULT (now() AT TIME ZONE 'UTC'),
  updated_by              integer             default 1
  );

CREATE SEQUENCE karvy_reverse_field_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TRIGGER last_updated BEFORE UPDATE ON karvy_reverse_field FOR EACH ROW EXECUTE PROCEDURE last_updated();
CREATE TRIGGER texple_audit AFTER INSERT OR UPDATE OR DELETE ON karvy_reverse_field FOR EACH ROW EXECUTE PROCEDURE texple_audit('karvy_reverse_field_log_id_seq');




CREATE SEQUENCE poa_rta_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE poa_rta_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



Drop table if exists poa_rta_list;
CREATE TABLE poa_rta_list (
    id bigint DEFAULT nextval('poa_rta_id_seq'::regclass) NOT NULL,
    regcode character varying(50),
    clientid character varying(50),
    clientname character varying(100),
    brokercode character varying(50),
    amccode character varying(50),
    schemecode character varying(50),
    securityname character varying(100),
    foliono character varying(50),
    trantype character varying(50),
    orderdate date,
    qty double precision,
    amount numeric,
    status character varying(50),
    remarks character varying(200),
    orderid character varying(50),
    usertrxnno character varying(50),
    poa character varying(50),
    poa_status character varying default 'generate', 
    poa_tiff_size  character varying default 'N/A',
    poa_downloaded_on timestamptz  DEFAULT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    created_by integer DEFAULT 1 NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_by integer DEFAULT 1 NOT NULL
);


Drop table if exists poa_rta_list_log;
CREATE TABLE poa_rta_list_log (
    log_id        BIGINT PRIMARY KEY,
    dml_action    char(1) NOT NULL CHECK (dml_action IN ('I', 'D', 'U')),
    log_timestamp timestamptz,
    id      bigint,
    regcode character varying(50),
    clientid character varying(50),
    clientname character varying(100),
    brokercode character varying(50),
    amccode character varying(50),
    schemecode character varying(50),
    securityname character varying(100),
    foliono character varying(50),
    trantype character varying(50),
    orderdate date,
    qty double precision,
    amount numeric,
    status character varying(50),
    remarks character varying(200),
    orderid character varying(50),
    usertrxnno character varying(50),
    poa character varying(50),
    poa_status character varying default 'generate', 
    poa_tiff_size  character varying default 'N/A',
    poa_downloaded_on timestamptz  DEFAULT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    created_by integer DEFAULT 1 NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_by integer DEFAULT 1 NOT NULL
);

CREATE TRIGGER last_updated BEFORE UPDATE ON poa_rta_list FOR EACH ROW EXECUTE PROCEDURE last_updated();
CREATE TRIGGER texple_audit AFTER INSERT OR UPDATE OR DELETE ON poa_rta_list FOR EACH ROW EXECUTE PROCEDURE texple_audit('poa_rta_log_id_seq');
