
CREATE SEQUENCE rta_reverse_feed_details_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

DROP TABLE IF EXISTS rta_reverse_feed_details;
CREATE TABLE rta_reverse_feed_details
(
  id          bigint PRIMARY KEY DEFAULT nextval('rta_reverse_feed_details_id_seq'::regclass),
reg_code character varying,
client_id integer,
client_name character varying,
broker_code varchar,
amc_code character varying,
scheme_code varchar,
security_name varchar,
folio_no double precision,
trant_type character varying,
order_date date,
qty integer,
amount integer,
status character varying,
remarks character varying,
order_id integer,
user_trxn_no integer,
  is_active				  boolean default true,
  created_at              timestamptz         DEFAULT (now() AT TIME ZONE 'UTC'),
  created_by              integer             default 1,
  updated_at              timestamptz         DEFAULT (now() AT TIME ZONE 'UTC'),
  updated_by              integer             default 1
);


drop table if exists rta_reverse_feed_details_log;
CREATE TABLE rta_reverse_feed_details_log
(
  log_id        BIGINT PRIMARY KEY,
  dml_action    char(1) NOT NULL CHECK (dml_action IN ('I', 'D', 'U')),
  log_timestamp timestamptz,
  id                          bigint,
 reg_code character varying
client_id integer,
client_name character varying,
broker_code varchar,
amc_code character varying,
scheme_code varchar,
security_name varchar,
folio_no double precision,
trant_type character varying,
order_date date,
qty integer,
amount integer,
status character varying,
remarks character varying,
order_id integer,
user_trxn_no integer,
  is_active					  boolean,
  created_at                  timestamptz,
  created_by                  integer,
  updated_at                  timestamptz,
  updated_by                  integer
);


CREATE SEQUENCE client_master_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


DROP TABLE IF EXISTS client_master;
CREATE TABLE client_master
(
  id          bigint PRIMARY KEY DEFAULT nextval('client_master'::
client_id integer,
client_name character varying,
client_code varchar,
client_type character varying,
account_type character varying,
account_open_date date,
inception_date date,
performance_reporting_date date,
charge_upto varchar
maturity_date date,
account_closure_date date,
account_closing_reason character varying,
birth_date date,
contact_name character varying,
phone_home integer,
phone_work integer,
mobile integer,
email character varying,
fax character varying,
address_1 varchar,
address_2 varchar,
city character varying,
pin_code integer,
state character varying,
mail_address_1 varchar,
mail_address_2 varchar,
mail_city character varying,
mail_pincode integer,
mail_state character varying,
pan_number character varying,
ward character varying,
circle character varying,
tan_number integer,
ref_code_1 character varying,
ref_code_2 character varying,
ref_code_3 character varying,
ref_code_4 character varying,
dir_1_name character varying,
dir_1_map_in varchar,
dir_2_name character varying,
dir_2_map_in varchar,
dir_3_name character varying,
dir_3_map_in varchar,
occupation character varying,
status character varying,
owner_id integer,
owner_name character varying,
group_id integer,
group_name character varying,
intermediary_id integer,
intermediary_name character varying,
scheme_id integer,
scheme_name character varying,
fund_mgr_id varchar,
fund_mgr_name character varying,
branch_id integer,
branch_name character varying,
rel_mgr_id char varying,
rel_mgr_name character varying,
advisor_id varchar,
advisor_name character varying,
user_name character varying,
broker_account_id varchar,
trading_bank_code varchar,
trading_bank_account varchar,
trading_custody_code varchar,
trading_custody_dp varchar,
trading_custody_account_id character varying,
client_bank_code varchar,
client_bank_account character varying,
client_custody_code varchar,
client_custody_dp varchar,
client_custody_account_id character varchar,
client_custody_scheme_code varchar,
bill_group varchar,
tds_on_fees double precision,
daily_expense_accrual varchar,
fee_payment_mode varchar,
incentive varchar,
mandate_bank_name character varying,
mandate_bank_branch_name character varying,
mandate_bank_account_type character varying,
mandate_bank_account_no varchar,
mandate_micr varchar,
mandate_rtgs varchar,
mandate_neft varchar,
mandate_depository varchar,
mandate_dp varchar,
mandated_pname character varying,
mandate_dp_client_id integer,
salutation character varying,
first_name character varying,
middle_name character varying,
last_name character varying,
first_holder_gender character varying,
father_husband_joint1_name character varying,
joint1_father_husband character varying,,
joint1_pan character varying,
joint2_name character varying,
joint2_father_husband character varying,
joint2_pan character varying,
nominee_name character varying,
guardian_name character varchar,
second_holder_name character varying,
second_holder_pan character varying,
second_holder_relation varchar,
second_holder_dob date,
second_holder_gender character varying,
second_holder_father_husband character varying,
second_holder_status character varying,
second_holder_occupation varchar,
second_holder_bank_name character varying,
second_holder_branch_name character varying,
second_holder_bank_account_no varchar,
second_holder_bank_acc.type character varying,
second_holder_micr_number integer,
second_holder_neft_code character varying,
second_holder_rtgs _code character varying,
second_holder_depository varchar,
second_holder_dp_id integer,
second_holder_dp_name character varying,
second_holder_dp_client_id integer
third_holder_name character varying,
third_holder_pan_no character varying,
third_holder_relation character varying,
third_holder_dob date,
third_holder_gender character varying,
third_holder_father_husband character varying,
third_holder_status character varying,
third_holder_occupation character varying,
third_holder_bank_name character varying,
third_holder_branch_name character varying,
third_holder_bank_account_no varchar,
third_holder_bank_acc.type character varying,
third_holder_micr_number character varying,
third_holder_neft_code character varying,
third_holder_rtgs_code character varying,
third_holder_depository character varying,
third_holder_dp_id character varying,
third_holder_dp_name character varying,
third_holder_dp_client_id integer
accounting_txn varchar,
stt_taken_as varchar,
trxn_taken_as varchar,
skip_from_mf_corporate_action varchar,
head_of_family character varying,
country character varying,
nationality character varying,
capital_committed varchar,
mail_phone_home integer,
mail_phone_work integer,
mail_mobile integer,
mail_fax varchar,
mail_email_id character varying,
share_reports_flag varchar,
arn_id character varying,
arn_name character varying,
wealth_advisor_id character varying,
wealth_advisor_name character varying,
first_holder_kyc character varying,
first_holder_aadhar integer,
first_holder_fatca character varying,
first_holder_ubo character varying,
second_holder_kyc character varying,
second_holder_aadhar integer,
second_holder_fatca character varying,
second_holder_ubo character varying,
third_holder_kyc character varying,
third_holder_aadhar integer,
third_holder_fatca character varying,
third_holder_ubo character varying,
mode_of_holding character varying,
   is_active				  boolean default true,
  created_at              timestamptz         DEFAULT (now() AT TIME ZONE 'UTC'),
  created_by              integer             default 1,
  updated_at              timestamptz         DEFAULT (now() AT TIME ZONE 'UTC'),
  updated_by              integer             default 1
  );

drop table if exists client_master_log;
CREATE TABLE client_master_log
(
log_id        BIGINT PRIMARY KEY,
  dml_action    char(1) NOT NULL CHECK (dml_action IN ('I', 'D', 'U')),
  log_timestamp timestamptz,
  id                          bigint,
client_id integer,
client_name character varying,
client_code varchar,
client_type character varying,
account_type character varying,
account_open_date date,
inception_date date,
performance_reporting_date date,
charge_upto varchar
maturity_date date,
accountt varchar,
closure_date_account date,
closing_reason character varying,
birth_date date,
contact_name character varying,
phone_home integer,
phone_work integer,
mobile integer,
email character varying,
fax character varying,
address_1 varchar,
address_2 varchar,
city character varying,
pin_code integer,
state character varying,
mail_address_1 varchar,
mail_address_2 varchar,
mail_city character varying,
mail_pincode integer,
mail_state character varying,
pan_number character varying,
ward character varying,
circle character varying,
tan_number integer,
ref_code_1 character varying,
ref_code_2 character varying,
ref_code_3 character varying,
ref_code_4 character varying,
dir_1_name character varying,
dir_1_map_in varchar,
dir_2_name character varying,
dir_2_map_in varchar,
dir_3_name character varying,
dir_3_map_in varchar,
occupation character varying,
status character varying,
owner_id integer,
owner_name character varying,
group_id integer,
group_name character varying,
intermediary_id integer,
intermediary_name character varying,
scheme_id integer,
scheme_name character varying,
fund_mgr_id varchar,
fund_mgr_name character varying,
branch_id integer,
branch_name character varying,
rel_mgr_id varchar,
rel_mgr_name character varying,
advisor_id varchar,
advisor_name character varying,
user_name character varying,
broker_account_id varchar,
trading_bank_code varchar,
trading_bank_account varchar,
trading_custody_code varchar,
trading_custody_dp varchar,
trading_custody_account_id character varying,
client_bank_code varchar,
client_bank_account character varying,
client_custody_code varchar,
client_custody_dp varchar,
client_custody_account_id character varchar,
client_custody_scheme_code varchar,
bill_group varchar,
tds_on_fees double precision,
daily_expense_accrual varchar,
fee_payment_mode varchar,
incentive varchar,
mandate_bank_name character varying,
mandate_bank_branch_name character varying,
mandate_bank_account_type character varying,
mandate_bank_account_no varchar,
mandate_micr varchar,
mandate_rtgs varchar,
mandate_neft varchar,
mandated_epository varchar,
mandate_dp varchar,
mandate_dp_name character varying,
mandate_dp_client_id integer,
salutation character varying,
first_name character varying,
middle_name character varying,
last_name character varying,
first_holder_gender character varying,
father_husband_joint1_name character varying,
joint1_father_husband character varying,,
joint1_pan character varying,
joint2_name character varying,
joint2_father_husband character varying,
joint2_pan character varying,
nominee_name character varying,
guardian_name character varchar,
second_holder_name character varying,
second_holder_pan character varying,
second_holder_relation varchar,
second_holder_dob date,
second_holder_gender character varying,
second_holder_father_husband character varying,
second_holder_status character varying,
second_holder_occupation varchar,
second_holder_bank_name character varying,
second_holder_branch_name character varying,
second_holder_bank_account_no varchar,
second_holder_bank_acc.type character varying,
second_holder_micr_number integer ,
second_holder_neft_code character varying,
second_holder_rtgs _code character varying,
second_holder_depository varchar,
second_holder_dp_id varchar,
second_holder_dp_name character varying,
second_holder_dp_client_id character varying,
third_holder_name character varying,
third_holder_pan_no character varying,
third_holder_relation character varying,
third_holder_dob date,
third_holder_gender character varying,
third_holder_father_husband character varying,
third_holder_status character varying,
third_holder_occupation character varying,
third_holder_bank_name character varying,
third_holder_branch_name character varying,
third_holder_bank_account_no varchar,
third_holder_bank_acc.type character varying,
third_holder_micr_number character varying,
third_holder_neft_code character varying,
third_holder_rtgs_code character varying,
third_holder_depository character varying,
third_holder_dp_id character varying,
third_holder_dp_name character varying,
third_holder_dp_client_id character varying,
accounting_txn varchar,
stt_taken_as varchar,
trxn_taken_as varchar,
skip_from_mf_corporate_action varchar,
head_of_family character varying,
country character varying,
nationality character varying,
capital_committed varchar,
mail_phone_home integer,
mail_phone_work integer,
mail_mobile integer,
mail_fax varchar,
mail_email_id character varying,
share_reports_flag varchar,
arn_id character varying,
arn_name character varying,
wealth_advisor_id character varying,
wealth_advisor_name character varying,
first_holder_kyc character varying,
first_holder_aadhar integer,
first_holder_fatca character varying,
first_holder_ubo character varying,
second_holder_kyc character varying,
second_holder_aadhar integer,
second_holder_fatca character varying,
second_holder_ubo character varying,
third_holder_kyc character varying,
third_holder_aadhar integer,
third_holder_fatca character varying,
third_holder_ubo character varying,
mode_of_holding character varying,


is_active					  boolean,
  created_at                  timestamptz,
  created_by                  integer,
  updated_at                  timestamptz,
  updated_by                  integer
  );


CREATE SEQUENCE client_master_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


CREATE TRIGGER last_updated BEFORE UPDATE ON client_master FOR EACH ROW EXECUTE PROCEDURE last_updated();
CREATE TRIGGER texple_audit AFTER INSERT OR UPDATE OR DELETE ON client_master FOR EACH ROW EXECUTE PROCEDURE texple_audit('client_master_log_id_seq');

CREATE SEQUENCE karvy_reverse_field_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
   DROP TABLE IF EXISTS karvy_reverse_field;
CREATE TABLE karvy_reverse_field
(
  id          bigint PRIMARY KEY DEFAULT nextval('karvy_reverse_field_id_seq'::regclass), 

portremarks character varying,
amc_code character varying,
broke_cd character varying,
sbbr_code character varying,
user_code character varying,
usr_txn_no integer,
appl_no integer,
folio_no integer,
ck_dig_no character varying,
trxn_type character varying,
sch_code character varying,
fh_name character varying,
j1_name character varying,
j2_name character varying,
add1 character varying,
add2 character varying,
add3 character varying,
city character varying,
pincode integer,
phone_off integer,
trxn_date date,
trxn_time timestamptz,
units integer,
amount double precision,
clos_ac_ch character varying,
fh_dob date,
guardian character varying,
tax_number character varying,
phone_res character varying,
fax_off varchar,
fax_res varchar,
email varchar,
acct_type character varying,
bank_name character varying,
br_name character varying,
bank_city character varying,
reinv_tag character varying,
hold_natur character varying,
occ_code integer,
tax_status integer,
remarks varchar,
state character varying,
sub_trxn_t character varying,
micr_cd varchar,
pay_mec character varying,
pricing varchar,
pan_2_hldr character varying,
pan_3_hldr character varying,
nom_name character varying,
nom_rela varchar,
guard_pan character varying,
fh_gndr varchar,
sip_rgdt varchar,
ifsc_code character varying,
mobile_no integer,
dp_id integer,
nri_add1 varchar,
nri_add2 varchar,
nri_add3 varchar,
nri_city character varying,
nri_state character varying,
nri_con varchar,
nom_per integer
nom2_name character varying,
nom2_rel character varying,
nom2_per integer
nom3_name character varying,
nom3_rel character varying,
nom3_per integer,
nri_add_fl character varying,
firc_stat character varying,
sip_rfno integer,
no_inst integer,
sip_fq character varying,
sip_st_dt character varying,
sip_end_dt character varying,
inst_num integer,
nom1_dob date,
nom1_min_f character varying,
nom1_guard character varying,
nom2_dob date,
nom2_min_f character varying,
nom2_guard character varying,
nom3_dob date,
nom3_min_f character varying,
nom3_guard character varying,
fh_pan_exm character varying,
j1_pan_exm character varying,
j2_pan_exm character varying,
gd_pan_exm character varying,
fh_exm_cat character varying,
j1_exm_cat character varying,
j2_exm_cat character varying,
gd_exm_cat character varying,
fh_kra_exm character varying,
j1_kra_exm character varying,
j2_kra_exm character varying,
gd_kra_exm character varying,
euin_opt character varying,
euin character varying,
nom_opt character varying,
sub_arn character varying,
iin_no integer,
fh_ckyc_no integer,
j1_ckyc_no integer,
j2_ckyc_no integer,
gd_ckyc_no integer,
j1_dob date,
j2_dob date,
gd_dob date,
brok_type character varying,
inv_dp_id character varying,
inv_pin_cd integer,
cust_const character varying,
log_wt varchar,
aof_ref character varying,
nri_soff varchar
fatca_flag character varying,
dpc character varying,
us_cn_dcl character varying,
isin character varying,
credit_fl character varying,
slf_fam_fl character varying,
stlmnt_no integer,
pap_les_fl character varying,
tac_flag character varying,
altmt_mode character varying,
sip_new character varying,
sip_amt integer,
ft_acno character varying,
depbank character varying,
dep_acno character varying,
dep_date date,
dep_rfno character varying,
suppl_flag character varying,
th_pty_pay character varying,
loc_cd character varying,
instr_no character varying,
kyc_flg character varying,
trxn_mode character varying,
dummy_1 character varying,
dummy_2 character varying,
dummy_3 character varying,
dummy_4 character varying,
dummy_5 character varying,
dummy_6 character varying,
dummy_7 character varying,
dummy_8 character varying,
dummy_9 character varying,
dummy_10 character varying,
dummy_11 character varying,
dummy_12 character varyinh,
dummy_13 character varying,
dummy_14 character varying,
dummy_15 character varying,
dummy_16 character varying,
dummy_17 character varying,
dummy_18 character varying,
dummy_19 character varying,
dummy_20 character varying,
dummy_21 character varying,
dummy_22 character varying,
dummy_23 character varying,
dummy_24 character varying,
dummy_25 character varying,
dummy_26 character varying,
dummy_27 character varying,
ih_no integer, 
transaction_date date
is_active				  boolean default true,
  created_at              timestamptz         DEFAULT (now() AT TIME ZONE 'UTC'),
  created_by              integer             default 1,
  updated_at              timestamptz         DEFAULT (now() AT TIME ZONE 'UTC'),
  updated_by              integer             default 1
  );

  drop table if exists karvy_reverse_field_log;
CREATE TABLE karvy_reverse_field_log
(
  log_id        BIGINT PRIMARY KEY,
  dml_action    char(1) NOT NULL CHECK (dml_action IN ('I', 'D', 'U')),
  log_timestamp timestamptz,
  id                          bigint,
portremarks character varying,
amc_code character varying,
broke_cd character varying,
sbbr_code character varying,
user_code character varying,
usr_txn_no integer,
appl_no integer,
folio_no integer,
ck_dig_no character varying,
trxn_type character varying,
sch_code character varying,
fh_name character varying,
j1_name character varying,
j2_name character varying,
add1 character varying,
add2 character varying,
add3 character varying,
city character varying,
pincode integer,
phone_off integer,
trxn_date date,
trxn_time timestamptz,
units integer,
amount integer,
clos_ac_ch character varying,
fh_dob date,
guardian character varying,
tax_number character varying,
phone_res character varying,
fax_off varchar,
fax_res varchar,
email varchar,
acct_type character varying,
bank_name character varying,
br_name character varying,
bank_city character varying,
reinv_tag character varying,
hold_natur character varying,
occ_code integer,
tax_status integer,
remarks varchar,
state character varying,
sub_trxn_t character varying,
micr_cd varchar,
pay_mec character varying,
pricing varchar,
pan_2_hldr character varying,
pan_3_hldr character varying,
nom_name character varying,
nom_rela varchar,
guard_pan character varying,
fh_gndr varchar,
sip_rgdt varchar,
ifsc_code character varying,
mobile_no integer,
dp_id integer,
nri_add1 varchar,
nri_add2 varchar,
nri_add3 varchar,
nri_city character varying,
nri_state character varying,
nri_con varchar,
nom_per integer
nom2_name character varying,
nom2_rel character varying,
nom2_per integer
nom3_name character varying,
nom3_rel character varying,
nom3_per integer,
nri_add_fl character varying,
firc_stat character varying,
sip_rfno integer,
no_inst integer,
sip_fq character varying,
sip_st_dt character varying,
sip_end_dt character varying,
inst_num integer,
nom1_dob date,
nom1_min_f character varying,
nom1_guard character varying,
nom2_dob date,
nom2_min_f character varying,
nom2_guard character varying,
nom3_dob date,
nom3_min_f character varying,
nom3_guard character varying,
fh_pan_exm character varying,
j1_pan_exm character varying,
j2_pan_exm character varying,
gd_pan_exm character varying,
fh_exm_cat character varying,
j1_exm_cat character varying,
j2_exm_cat character varying,
gd_exm_cat character varying,
fh_kra_exm character varying,
j1_kra_exm character varying,
j2_kra_exm character varying,
gd_kra_exm character varying,
euin_opt character varying,
euin character varying,
nom_opt character varying,
sub_arn character varying,
iin_no integer,
fh_ckyc_no integer,
j1_ckyc_no integer,
j2_ckyc_no integer,
gd_ckyc_no integer,
j1_dob date,
j2_dob date,
gd_dob date,
brok_type character varying,
inv_dp_id character varying,
inv_pin_cd integer,
cust_const character varying,
log_wt varchar,
aof_ref character varying,
nri_soff varchar
fatca_flag character varying,
dpc character varying,
us_cn_dcl character varying,
isin character varying,
credit_fl character varying,
slf_fam_fl character varying,
stlmnt_no integer,
pap_les_fl character varying,
tac_flag character varying,
altmt_mode character varying,
sip_new character varying,
sip_amt integer,
ft_acno character varying,
depbank character varying,
dep_acno character varying,
dep_date date,
dep_rfno character varying,
suppl_flag character varying,
th_pty_pay character varying,
loc_cd character varying,
instr_no character varying,
kyc_flg character varying,
trxn_mode character varying,
dummy_1 character varying,
dummy_2 character varying,
dummy_3 character varying,
dummy_4 character varying,
dummy_5 character varying,
dummy_6 character varying,
dummy_7 character varying,
dummy_8 character varying,
dummy_9 character varying,
dummy_10 character varying,
dummy_11 character varying,
dummy_12 character varyinh,
dummy_13 character varying,
dummy_14 character varying,
dummy_15 character varying,
dummy_16 character varying,
dummy_17 character varying,
dummy_18 character varying,
dummy_19 character varying,
dummy_20 character varying,
dummy_21 character varying,
dummy_22 character varying,
dummy_23 character varying,
dummy_24 character varying,
dummy_25 character varying,
dummy_26 character varying,
dummy_27 character varying,
ih_no integer, 
transaction_date date
 is_active					  boolean,
  created_at                  timestamptz,
  created_by                  integer,
  updated_at                  timestamptz,
  updated_by                  integer
);
CREATE SEQUENCE client_master_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
    
CREATE TRIGGER last_updated BEFORE UPDATE ON karvy_reverse_field FOR EACH ROW EXECUTE PROCEDURE last_updated();
CREATE TRIGGER texple_audit AFTER INSERT OR UPDATE OR DELETE ON karvy_reverse_field FOR EACH ROW EXECUTE PROCEDURE texple_audit('karvy_reverse_field_log_id_seq');


