from app import db

class nominee_karvy_reverse_field(db.Model):
    __tablename__ = 'karvy_reverse_field'
    id = db.Column(db.Integer, primary_key=True)
    portremarks = db.Column (db.String())
    amc_code = db.Column(db.String())
    broke_cd = db.Column(db.String())
    sbbr_code = db.Column(db.String())
    user_code = db.Column(db.String())
    usr_txn_no = db.Column(db.Numeric())
    appl_no = db.Column(db.Numeric())
    folio_no = db.Column(db.Numeric())
    ck_dig_no = db.Column(db.String())
    trxn_type = db.Column(db.String())
    sch_code = db.Column(db.String())
    fh_name = db.Column(db.String())
    j1_name = db.Column(db.String())
    j2_name = db.Column(db.String())
    add1= db.Column(db.String())
    add2= db.Column(db.String())
    add3= db.Column(db.String())
    city = db.Column (db.String())
    pincode= db.Column(db.Numeric())
    phone_off= db.Column(db.Numeric())
    trxn_date= db.Column(db.String())
    trxn_time = db.Column(db.String())
    units = db.Column(db.Numeric())
    amount = db.Column(db.Numeric())
    clos_ac_ch = db.Column(db.String())
    fh_dob = db.Column (db.String())
    guardian= db.Column(db.String())
    tax_number = db.Column(db.Numeric())
    phone_res = db.Column(db.String())
    fax_off = db.Column(db.String())
    fax_res = db.Column(db.String())
    email= db.Column(db.String())
    acc_no = db.Column(db.String())
    acct_type= db.Column(db.String())
    bank_name = db.Column(db.String())
    br_name = db.Column(db.String())
    bank_city = db.Column(db.String())
    reinv_tag = db.Column(db.String())
    hold_natur= db.Column(db.String())
    occ_code = db.Column(db.Numeric())
    tax_status = db.Column(db.Numeric())
    remarks = db.Column(db.String())
    state= db.Column(db.String())
    sub_trxn_t= db.Column(db.String())
    micr_cd = db.Column (db.String())
    pay_mec = db.Column(db.String())
    pricing = db.Column(db.String())
    pan_2_hldr = db.Column(db.String())
    pan_3_hldr = db.Column(db.String())
    nom_name = db.Column(db.String())
    nom_rela = db.Column(db.String())
    guard_pan= db.Column(db.String())
    fh_gndr= db.Column(db.String())
    sip_rgdt= db.Column(db.String())
    ifsc_code = db.Column(db.String())
    mobile_no = db.Column(db.Numeric())
    dp_id = db.Column(db.Numeric())
    nri_add1 = db.Column(db.String())
    nri_add2 = db.Column(db.String())
    nri_add3 = db.Column(db.String())
    nri_city = db.Column(db.String())
    nri_state = db.Column(db.String())
    nri_con = db.Column(db.String())
    nri_pin = db.Column(db.String())
    nom_per = db.Column(db.Numeric())
    nom2_name = db.Column(db.String())
    nom2_rel = db.Column(db.String())
    nom2_per = db.Column(db.Numeric())
    nom3_name = db.Column(db.String())
    nom3_rel = db.Column(db.String())
    nom3_per = db.Column(db.Numeric())
    nri_add_fl= db.Column(db.String())
    firc_stat= db.Column(db.String())
    sip_rfno = db.Column(db.Numeric())
    no_inst = db.Column(db.Numeric())
    sip_fq = db.Column(db.String())
    sip_st_dt = db.Column(db.String())
    sip_end_dt = db.Column(db.String())
    inst_num = db.Column(db.Numeric())
    nom1_dob = db.Column(db.String())
    nom1_min_f = db.Column(db.String())
    nom1_guard = db.Column(db.String())
    nom2_dob = db.Column(db.String())
    nom2_min_f= db.Column(db.String())
    nom2_guard = db.Column (db.String())
    nom3_dob = db.Column (db.String())
    nom3_min_f = db.Column (db.String())
    nom3_guard = db.Column (db.String())
    fh_pan_exm = db.Column (db.String())
    j1_pan_exm = db.Column (db.String())
    j2_pan_exm = db.Column (db.String())
    gd_pan_exm = db.Column (db.String())
    fh_exm_cat = db.Column (db.String())
    j1_exm_cat = db.Column (db.String())
    j2_exm_cat = db.Column (db.String())
    gd_exm_cat = db.Column (db.String())
    fh_kra_exm =  db.Column (db.String())
    j1_kra_exm = db.Column (db.String())
    j2_kra_exm = db.Column (db.String())
    gd_kra_exm = db.Column (db.String())
    euin_opt = db.Column (db.String())
    euin = db.Column (db.String())
    nom_opt = db.Column (db.String())
    sub_arn = db.Column (db.String())
    iin_no = db.Column (db.Numeric())
    fh_ckyc_no =db.Column (db.Numeric())
    j1_ckyc_no = db.Column (db.Numeric())
    j2_ckyc_no = db.Column (db.Numeric())
    gd_ckyc_no = db.Column (db.Numeric())
    j1_dob = db.Column (db.String())
    j2_dob = db.Column (db.String())
    gd_dob = db.Column (db.String())
    brok_type =db.Column (db.String())
    inv_dp_id = db.Column (db.String())
    inv_pin_cd = db.Column (db.Numeric())
    cust_const = db.Column (db.String())
    log_wt = db.Column (db.String())
    aof_ref  =db.Column (db.String())
    nri_soff =db.Column (db.String())
    fatca_flag =db.Column (db.String())
    dpc = db.Column (db.String())
    us_cn_dcl = db.Column (db.String())
    isin = db.Column (db.String())
    credit_fl = db.Column (db.String())
    slf_fam_fl = db.Column (db.String())
    stlmnt_no = db.Column (db.Numeric())
    pap_les_fl = db.Column (db.String())
    tac_flag = db.Column (db.String())
    altmt_mode = db.Column (db.String())
    sip_new = db.Column (db.String())
    sip_amt =db.Column (db.Numeric())
    ft_acno = db.Column (db.String())
    depbank = db.Column (db.String())
    dep_acno = db.Column (db.String())
    dep_date = db.Column (db.String())
    dep_rfno = db.Column (db.String())
    suppl_flag= db.Column (db.String())
    th_pty_pay= db.Column (db.String())
    loc_cd = db.Column (db.String())
    instr_no =db.Column (db.String())
    kyc_flg =db.Column (db.String())
    trxn_mode = db.Column (db.Numeric())
    dummy_1 = db.Column (db.String())
    dummy_2 = db.Column (db.Numeric())
    dummy_3 = db.Column (db.String())
    dummy_4 = db.Column (db.String())
    dummy_5 = db.Column (db.String())
    dummy_6 = db.Column (db.String()) 
    dummy_7 = db.Column (db.String()) 
    dummy_8 = db.Column (db.String())
    dummy_9 = db.Column (db.String())
    dummy_10 = db.Column (db.String()) 
    dummy_11 = db.Column (db.String())
    dummy_12 = db.Column (db.String())
    dummy_13 = db.Column (db.String())
    dummy_14 = db.Column (db.String())
    dummy_15 = db.Column (db.String())
    dummy_16 = db.Column (db.String())
    dummy_17 = db.Column (db.String())
    dummy_18 = db.Column (db.String())
    dummy_19 = db.Column (db.String())
    dummy_20 = db.Column (db.String())
    dummy_21 = db.Column (db.String())
    dummy_22 = db.Column (db.String())
    dummy_23 = db.Column (db.String())
    dummy_24 = db.Column (db.String())
    dummy_25 = db.Column (db.String())
    dummy_26 = db.Column (db.String())
    dummy_27 = db.Column (db.String())
    ih_no = db.Column (db.Numeric())
    transaction_date = db.Column (db.String())

    def __init__(self, data):
        if data[0] != '':
            self.portremarks = data[0]
        if data[1] != '': 
            self.amc_code = data[1]
        if data[2] != '': 
            self.broke_cd = data[2]
        if data[3] != '': 
            self.sbbr_code = data[3]
        if data[4] != '':
            self.user_code= data[4]
        if data[5] != '': 
            self.usr_txn_no = data[5] 
        if data[6] != '':   
            self.appl_no = data[6]
        if data[7] != '':
            self.folio_no = data[7] 
        if data[8] != '':  
            self.ck_dig_no= data[8]
        if data[9] != '': 
            self.trxn_type = data[9]
        if data[10] != '':
            self.sch_code = data[10] 
        if data[11] != '': 
            self.fh_name = data[11]
        if data[12] != '':
            self.j1_name = data[12]
        if data[13] != '': 
            self.j2_name = data[13]
        if data[14] != '':
            self.add1 = data [14]
        if data[15] != '':
            self.add2 = data[15]
        if data[16] != '': 
            self.add3 = data[16]
        if data[17] != '': 
            self.city= data[17]
        if data[18] != '': 
            self.pincode = data[18]
        if data[19] != '':
            self.phone_off = data[19]
        if data[20] != '':
            self.trxn_date	= data[20]
        if data[21] != '': 
            self.trxn_time  = data[21] 
        if data[22] != '':   
            self.units  = data[22]
        if data[23] != '':
            self.amount  = data[23] 
        if data[24] != '':  
            self.clos_ac_ch = data[24]
        if data[25] != '': 
            self.fh_dob  = data[25]
        if data[26] != '':
            self.guardian = data[26] 
        if data[27] != '': 
            self.tax_number = data[27]
        if data[28] != '':
            self.phone_res = data[28]
        if data[29] != '': 
            self.fax_off = data[29]
        if data[30] != '':
            self.fax_res= data [30]
        if data[31] != '':
            self.email = data [31]
        if data[32] != '':
            self.acct_no = data[32]
        if data[33] != '': 
            self.acct_type	= data[33]
        if data[34] != '': 
            self.bank_name  = data[34]
        if data[35] != '': 
            self.br_name = data[35]
        if data[36] != '':
            self.bank_city	= data[36]
        if data[37] != '': 
            self.reinv_tag	= data[37] 
        if data[38] != '':   
            self.hold_natur = data[38]
        if data[39] != '':
            self.occ_code = data[39] 
        if data[40] != '':  
            self.tax_status = data[40]
        if data[41] != '': 
            self.remarks= data[41]
        if data[42] != '':
            self.state = data[42] 
        if data[43] != '': 
            self.sub_trxn_t = data[43]
        if data[44] != '':
            self.micr_cd = data[44]
        if data[45] != '': 
            self.pay_mec = data[45]
        if data[46] != '':
            self.pricing = data [46]
        if data[47] != '':
            self.pan_2_hldr = data[47]
        if data[48] != '':
            self.pan_3_hldr = data[48]
        if data[49] != '':
            self.nom_name = data[49]
        if data[50] != '':
            self.nom_rela = data[50]
        if data[51] != '':
            self.guard_pan = data[51]
        if data[52] != '':
            self.fh_gndr = data[52]
        if data[53] != '':
            self.sip_rgdt = data[53]
        if data[54] != '':
            self.ifsc_code = data[54]
        if data[55] != '':
            self.mobile_no = data[55]
        if data[56] != '':
            self.dp_id = data[56]
        if data[57] != '':
            self.nri_add1 = data[57]
        if data[58] != '':
            self.nri_add2  = data[58]
        if data[59] != '':
            self.nri_add3= data[59]
        if data[60] != '':
            self.nri_city = data[60]
        if data[61] != '':
            self.nri_state= data[61]
        if data[62] != '':
            self.nri_con = data[62]
        if data[63] != '':
            self.nri_pin  = data[63]
        if data[64] != '':
            self.nom_per = data[64]
        if data[65] != '':
            self.nom2_name = data[65]
        if data[66] != '':
            self.nom2_rel= data[66]
        if data[67] != '':
            self.nom2_per = data[67]
        if data[68] != '':
            self.nom3_name = data[68]
        if data[69] != '':
            self.nom3_rel = data[69]
        if data[70] != '':
            self.nom3_per  = data[70]
        if data[71] != '':
            self.nri_add_fl = data[71]
        if data[72] != '':
            self.firc_stat = data[72]
        if data[73] != '':
            self.sip_rfno = data[73]
        if data[74] != '':
            self.no_inst = data[74]
        if data[75] != '':
            self.sip_fq = data[75]
        if data[76] != '':
            self.sip_st_dt = data[76]
        if data[77] != '':
            self.sip_end_dt = data[77]
        if data[78] != '':
            self.inst_num  = data[78]
        if data[79] != '':
            self.nom1_dob = data[79]
        if data[80] != '':
            self.nom1_min_f = data[80]
        if data[81] != '':
            self.nom1_guard = data[81]
        if data[82] != '':
            self.nom2_dob = data[82]
        if data[83] != '':
            self.nom2_min_f = data[83]
        if data[84] != '':
            self.nom2_guard= data[84]
        if data[85] != '':
            self.nom3_dob = data[85]
        if data[86] != '':
            self.nom3_min_f= data[86]
        if data[87] != '':
            self.nom3_guard = data[87]
        if data[88] != '':
            self.fh_pan_exm = data[88]
        if data[89] != '':
            self.j1_pan_exm = data[89]
        if data[90] != '':
            self.j2_pan_exm  = data[90]
        if data[91] != '':
            self.gd_pan_exam = data[91]
        if data[92] != '':
            self.fh_exm_cat = data[92]
        if data[93] != '':
            self.j1_exm_cat  = data[93]
        if data[94] != '':
            self.j2_exm_cat = data[94]
        if data[95] != '':
            self.gd_exm_cat = data[95]
        if data[96] != '':
            self.fh_kra_exm = data[96]
        if data[97] != '':
            self.j1_kra_exm= data[97]
        if data[98] != '':
            self.j2_kra_exm = data[98]
        if data[99] != '':
            self.gd_kra_exm = data[99]
        if data[100] != '':
            self.euin_opt = data[100]
        if data[101] != '':
            self.euin  = data[101]
        if data[102] != '':
            self.nom_opt  = data[102]
        if data[103] != '':
            self.sub_arn = data[103]
        if data[104] != '':
            self.iin_no = data[104]
        if data[105] != '':
            self.fh_ckyc_no = data[105]
        if data[106] != '':
            self.j1_ckyc_no = data[106]
        if data[107] != '':
            self.j2_ckyc_no = data[107]
        if data[108] != '':
            self.gd_ckyc_no = data[108]  
        if data[109] != '':
            self.j1_dob = data[109]
        if data[110] != '':
            self.j2_dob = data[110]
        if data[111] != '':
            self.gd_dob = data[111]
        if data[112] != '':
            self.brok_type = data[112]
        if data[113] != '':
            self.inv_dp_id = data[113]
        if data[114] != '':
            self.inv_pin_cd  = data[114]
        if data[115] != '':
            self.cust_const = data[115]
        if data[116] != '':
            self.log_wt  = data[116]
        if data[117] != '':
            self.aof_ref= data[117]
        if data[118] != '':
            self.nri_sof = data[118]
        if data[119] != '':
            self.fatca_flag = data[119]
        if data[120] != '':
            self.dpc = data[120]
        if data[121] != '':
            self.us_cn_dcl = data[121]
        if data[122] != '':
            self.isin = data[122]
        if data[123] != '':
            self.credit_fl = data[123]
        if data[124] != '':
            self.slf_fam_fl	 = data[124]
        if data[125] != '':
            self.stlmnt_no = data[125]
        if data[126] != '':
            self.pap_les_fl = data[126]
        if data[127] != '':
            self.tac_flag = data[127]
        if data[128] != '':
            self.altmt_mode = data[128]
        if data[129] != '':
            self.sip_new = data[129]
        if data[130] != '':
            self.sip_amt = data[130], 
        if data[131] != '':
            self.ft_acno = data[131]
        if data[132] != '':
            self.depbank   = data[132]
        if data[133] != '':
            self.dep_acno = data[133]
        if data[134] != '':
            self.dep_date = data[134]
        if data[135] != '':
            self.dep_rfno = data[135]
        if data[136] != '':
            self.suppl_flag = data[136]
        if data[137] != '':
            self.th_pty_pay = data[137]
        if data[138] != '':
            self.loc_cd = data[138]
        if data[139] != '':
            self.instr_no = data[139]
        if data[140] != '':
            self.kyc_flg = data[140]
        if data[141] != '':
            self.trxn_mode = data[141]
        if data[142] != '':
            self.dummy1 = data[142]
        if data[143] != '':
            self.dummy_2= data[143]
        if data[144] != '':
            self.dummy_3 = data[144]
        if data[145] != '':
            self.dummy_4 = data[145]
        if data[146] != '':
            self.dummy_5 = data[146]
        if data[147] != '':
            self.dummy_6= data[147]
        if data[148] != '':
            self.dummy_7= data[148]
        if data[149] != '':
            self.dummy_8 = data[149]
        if data[150] != '':
            self.dummy_9 = data[150]
        if data[151] != '':
            self.dummy_10= data[151]
        if data[152] != '':
            self.dummy_11= data[152]
        if data[153] != '':
            self.dummy_12 = data[153]
        if data[154] != '':
            self.dummy_13 = data[154]
        if data[155] != '':
            self.dummy_14= data[155]
        if data[156] != '':
            self.dummy_15 = data[156]
        if data[157] != '':
            self.dummy_16  = data[157]
        if data[158] != '':
            self.dummy_17 = data[158]
        if data[159] != '':
            self.dummy_18 = data[159]
        if data[160] != '':
            self.dummy_19 = data[160]
        if data[161] != '':
            self.dummy_20 = data[161]
        if data[162] != '':
            self.dummy_21 = data[162]
        if data[163] != '':
            self.dummy_22 = data[163]
        if data[164] != '':
            self.dummy_23 = data[164]
        if data[165] != '':
            self.dummy_24 = data[165]
        if data[166] != '': 
            self.dummy_25 = data[166]
        if data[167] != '': 
            self.dummy_26 = data[167]
        if data[168] != '': 
            self.dummy_27 = data[168]
        if data[169] != '': 
            self.ih_no = data[169]        
        if data[170] != '': 
            self.transaction_date = data[170]
            # x = datetime.datetime.data()
            # print(x)
            # self.transaction_date =x
            
            # self.transaction_date = data[169]



    
            
        
        